version: "2"
services:
    wp:
        extends:
            file: common.yml
            service: wp
        volumes:
            - ./dist:/var/www/wp-content/themes/dev-theme
        ports:
            - 8080:80
    build:
        extends:
            file: common.yml
            service: build
        volumes:
            - ./src:/app/src
            - ./dist:/app/dist
        command: npm run watch